void mrecv_gc();
void mrecv(int s);
static mfile *mrecv_mfdel(mfile *m);
static int    mrecv_packet(int s, mdata *data, struct sockaddr_in *addr);
static void   mrecv_ping(mdata *data, struct sockaddr_in *addr);
static void   mrecv_exit(mdata *data, struct sockaddr_in *addr);
static int    mrecv_file_data(mfile *m,  mdata *r);
static int    mrecv_file_break(mfile *m, mdata *r);
static int    mrecv_file_open(mfile *m, mdata *r);
static int    mrecv_file_close(mfile *m, mdata *r);
static int    mrecv_file_mark(mfile *m, mdata *r);
static int    mrecv_file_next(mfile *m,  mdata *r);
static mfile *mrecv_file_stat(mdata *data, struct sockaddr_in *addr);
static void   mrecv_file(mdata *data, struct sockaddr_in *addr);
static void   mrecv_ack_file(mfile *m, mhost *h, mdata *data);
static void   mrecv_ack_md5(mfile *m, mhost *h, mdata *data);
static void   mrecv_ack(mdata *data, struct sockaddr_in *addr);
static void   mrecv_md5_open(mfile *m, mdata *data, struct sockaddr_in *addr);
static void   mrecv_md5_close(mfile *m, mdata *data, struct sockaddr_in *addr);
static void   mrecv_md5(mdata *data, struct sockaddr_in *addr);
static int    mrecv_decrypt(mdata *data, struct sockaddr_in *addr);
